companyFilling/changeDirector/routes.py
from flask import render_template, url_for, flash, redirect, send_file, Blueprint, abort, request
from flask_login import login_user, current_user, logout_user, login_required
from companyFilling.model import Company, DirectorResignation, Director, TestDB, DirectorChangeResolution, DirectorChange
from companyFilling import db
from companyFilling.changeDirector.forms import DirectorInfo, Test
import os
import uuid
from datetime import date

changeDirector = Blueprint('changeDirector', __name__)


@changeDirector.route('add_director/<company_id>', methods=['GET', "POST"])
@login_required
def add_director(company_id):
    company = Company.query.filter_by(id=company_id).first()
    if company.owner_id != current_user.id:
        abort(403)

    form = DirectorInfo()
    if form.validate_on_submit():
        # if request.form.get("reason") == "AlternateDirector":
        #     alternateToWho = request.form.get('alternateTo')
        today = date.today()

        newDirector = Director(company_id=company_id, directorNameInChinese=form.directorNameInChinese.data,
                               directorSurname=form.directorSurname.data, directorOtherName=form.directorOtherName.data,
                               hkidCardNumber=form.hkidCardNumber.data,
                               directorEmail=form.directorEmail.data, passportIssuingCountry=form.passportIssuingCountry.data,
                               passportNumber=form.passportNumber.data, companyOwnerID=current_user.id,
                               companyOrPerson="Natural Person", capacity=request.form.get("reason"),
                               alternateTo=request.form.get('alternateTo'), address1=form.address1.data,
                               address2=form.address2.data, address3=form.address3.data,
                               dateAdded=today.strftime("%B %d, %Y"), active="active")

        db.session.add(newDirector)
        db.session.commit()

        from datetime import datetime
        now = datetime.now()
        message = f"""Date add: {now.strftime("%d %B, %Y")}
Director English Name: {form.directorOtherName.data} {form.directorSurname.data}
Director Chinese Name: {form.directorNameInChinese.data}
Director Email: {form.directorEmail.data}
"""
        with open(f"companyFilling/companyDirectorChangeLog/{company_id}.txt", 'a') as file:
            file.write(message)
            file.write('\n')

        return redirect(url_for('fillingForm.edit_company_info', company_id=company_id))

    return render_template("changeDirector/addDirector.html", form=form)


@changeDirector.route('add_director_corp/<company_id>', methods=['GET', "POST"])
@login_required
def add_director_corp(company_id):
    company = Company.query.filter_by(id=company_id).first()
    if company.owner_id != current_user.id:
        abort(403)

    form = DirectorInfo()
    if form.validate_on_submit():
        today = date.today()
        newDirector = Director(company_id=company_id, directorNameInChinese=form.directorNameInChinese.data,
                               directorOtherName=form.englishName.data, directorEmail=form.directorEmail.data,
                               companyOwnerID=current_user.id, companyOrPerson="Corporate", capacity=request.form.get("reason"),
                               alternateTo=request.form.get('alternateTo'), companyNumber=form.companyNumber.data,
                               address1=form.address1.data, address2=form.address2.data,
                               address3=form.address3.data, dateAdded=today.strftime("%B %d, %Y"),
                               active="active", directorSurname=""
                               )

        db.session.add(newDirector)
        db.session.commit()

        return redirect(url_for('fillingForm.edit_company_info', company_id=company_id))

    return render_template("changeDirector/addDirectorCorp.html", form=form)


@changeDirector.route('remove_director/<company_id>', methods=['GET', "POST"])
@login_required
def remove_director(company_id):
    directors = Director.query.filter_by(company_id=company_id, active='active')

    director = Director.query.filter_by(company_id=company_id).first()
    if current_user.id != director.companyOwnerID:
        abort(403)

    return render_template("changeDirector/removeDirector.html", directors=directors, company_id=company_id)


@changeDirector.route("remove/<director_id>")
@login_required
def resign(director_id):
    director = Director.query.filter_by(id=director_id).first()
    company = Company.query.filter_by(id=director.company_id).first()

    if company.owner_id != current_user.id:
        abort(403)

    from datetime import datetime
    now = datetime.now()
    director.active = "non-active"

    changeInDirector = DirectorChange(company_id=company.id, date=f"{now.strftime('%d %B, %Y')}",
                                      resignDirector=f"{director.directorOtherName} {director.directorSurname}",
                                      reason="resign")
    db.session.add(changeInDirector)

    from uuid import uuid4
    uuid_string = str(uuid4())
    newResignation = DirectorResignation(owner_id=current_user.id, uuid=uuid_string,
                                         company_id=company.id, companyName=company.companyName,
                                         resignDirector=f"{director.directorOtherName} {director.directorSurname}",
                                         date_passed_resolution=f"{now.strftime('%d %B, %Y')}")
    db.session.add(newResignation)
    db.session.commit()

    xml = ""
    if director.companyOrPerson == "Natural Person" and director.capacity == "Director":
        xml = f"""<Eform xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CR-Format.xsd" id="ND4">
    <TextField id="language">E</TextField>
    <TextField id="hiddenCompNo">{company.companyNumber}</TextField>
    <TextField id="compName">{company.companyName} </TextField>
    <TextField id="S2CapacityGroup1">false</TextField>
    <TextField id="S2CapacityGroup2">true</TextField>
    <TextField id="S2CapacityGroup3">false</TextField>
    <TextField id="S2alternateTo"/>
    <TextField id="S2chnName">{director.directorNameInChinese}</TextField>
    <TextField id="S2engSurname">{director.directorSurname}</TextField>
    <TextField id="S2engOthName">{director.directorOtherName}</TextField>
    <TextField id="S2HKID">{director.hkidCardNumber}</TextField>
    <TextField id="S2PPTNo">{director.passportNumber}</TextField>
    <TextField id="S2corpChnName"/>
    <TextField id="S2corpEngName"/>
    <TextField id="S2ResignDate">{now.strftime("%Y%m%d")}</TextField>
    <TextField id="S2cessContGroup">S2cessContGroup2</TextField>
    <TextField id="S2corpCompNo"/>
    <TextField id="S3regNoticeGroup">S3regNoticeGroup1</TextField>
    <TextField id="nameCRNo">{director.directorNameInChinese}##{director.directorSurname}, {director.directorOtherName}##</TextField>
    <TextField id="signatoryCRNo"/>
    <TextField id="nameCapacity">{director.directorNameInChinese}##{director.directorSurname}, {director.directorOtherName}##D</TextField>
    <TextField id="signCapacity">{director.capacity}</TextField>
    <TextField id="signName">{director.directorSurname}, {director.directorOtherName}</TextField>
    <TextField id="signDate">{now.strftime("%Y%m%d")}</TextField>
    </Eform>
        """
    elif director.companyOrPerson == "Natural Person" and director.capacity == "AlternateDirector":
        xml = f"""<Eform xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CR-Format.xsd" id="ND4">
    <TextField id="language">E</TextField>
    <TextField id="hiddenCompNo">{company.companyNumber}</TextField>
    <TextField id="compName">{company.companyName} </TextField>
    <TextField id="S2CapacityGroup1">false</TextField>
    <TextField id="S2CapacityGroup2">false</TextField>
    <TextField id="S2CapacityGroup3">true</TextField>
    <TextField id="S2alternateTo">{director.alternateTo}</TextField>
    <TextField id="S2chnName">{director.directorNameInChinese}</TextField>
    <TextField id="S2engSurname">{director.directorSurname}</TextField>
    <TextField id="S2engOthName">{director.directorOtherName}</TextField>
    <TextField id="S2HKID">{director.hkidCardNumber}</TextField>
    <TextField id="S2PPTNo">{director.passportNumber}</TextField>
    <TextField id="S2corpChnName"/>
    <TextField id="S2corpEngName"/>
    <TextField id="S2ResignDate">{now.strftime("%Y%m%d")}</TextField>
    <TextField id="S2cessContGroup">S2cessContGroup2</TextField>
    <TextField id="S2corpCompNo"/>
    <TextField id="S3regNoticeGroup">S3regNoticeGroup1</TextField>
    <TextField id="nameCRNo">{director.directorNameInChinese}##{director.directorSurname}, {director.directorOtherName}##</TextField>
    <TextField id="signatoryCRNo"/>
    <TextField id="nameCapacity">{director.directorNameInChinese}## {director.directorSurname}, {director.directorOtherName}##D</TextField>
    <TextField id="signCapacity">{director.capacity}</TextField>
    <TextField id="signName">{director.directorSurname}, {director.directorOtherName}</TextField>
    <TextField id="signDate">{now.strftime("%Y%m%d")}</TextField>
    </Eform>
        """

    elif director.companyOrPerson == "Corporate" and director.capacity=="Director":
        xml = f"""<Eform xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CR-Format.xsd" id="ND4">
            <TextField id="language">E</TextField>
            <TextField id="hiddenCompNo">{company.companyNumber}</TextField>
            <TextField id="compName">{company.companyName} </TextField>
            <TextField id="S2CapacityGroup1">false</TextField>
            <TextField id="S2CapacityGroup2">true</TextField>
            <TextField id="S2CapacityGroup3">false</TextField>
            <TextField id="S2alternateTo"/>
            <TextField id="S2chnName"/>

companyFilling/fillingForm/routes.py
from flask import render_template, url_for, flash, redirect, send_file, Blueprint, abort, request
from flask_login import login_user, current_user, logout_user, login_required
from companyFilling.model import Company, Nar1data, User
from companyFilling import db
from companyFilling.fillingForm.forms import Nar1Form, AddCompany, aButton, CompanyInfo
import os


fillingForm = Blueprint('fillingForm', __name__)


@fillingForm.route('')
@login_required
def home():
    return render_template('userPage.html', name=current_user.username)


@fillingForm.route('all_company/<company_id>', methods=['GET', 'POST'])
@login_required
def all_form(company_id):
    # only allow to view company that they create
    selectedCompany = Company.query.filter_by(id=company_id).first()

    if str(current_user.id) != str(selectedCompany.owner_id):
        abort(403)

    else:
        form = aButton()
        companyForm = Nar1data.query.filter_by(company_id=company_id)

        #if form.validate_on_submit():
        if request.form:
            return redirect(url_for('fillingForm.fill_nar1_form', company_id=selectedCompany.id))

        return render_template('addForm.html', form=form, companyForm=companyForm)


@fillingForm.route('all_company/<company_id>/nar1_form', methods=["POST", 'GET'])
@login_required
def fill_nar1_form(company_id):
    form = Nar1Form()
    if form.validate_on_submit():
        newNar1 = Nar1data(company_id=company_id, companyName=form.companyName.data,
                       S2compName=form.S2compName.data, typeOfCompany=form.companyType.data,
                       date1=form.date1.data, financialStatementStartDate=form.financialStatementStartDate.data,
                       financialStatementEndDate=form.financialStatementEndDate.data, registeredOfficeAddress=form.registeredOfficeAddress.data,
                       emailAddress=form.emailAddress.data, mortgagesCharges=form.mortgagesCharges.data,
                       q9=form.q9.data)
        db.session.add(newNar1)
        db.session.commit()
        return redirect(url_for('fillingForm.home'))

    return render_template('nar1formTest.html', form=form, name=current_user.username)


@fillingForm.route('nar1_download/<form_number>', methods=["POST", "GET"])
@login_required
def nar1_pdf_download(form_number):
    selectedForm = Nar1data.query.filter_by(id=form_number).first()
    formOwner = Company.query.filter_by(id=selectedForm.company_id).first()

    if current_user.id != formOwner.owner_id:
       abort(403)

    else:
        from companyFilling import generatePdf
        generatePdf.changeNAR1Form(form_number, ['', selectedForm.companyName, selectedForm.businessName,  # 0-2
                                                selectedForm.date1, selectedForm.registeredOfficeAddress, '456' # 3-5
                                                 ])


        pdfDir = os.getcwd() + f'\\companyFilling\\static\\pdfFile\\nar1_company_form\\{form_number}.pdf'
        return send_file(pdfDir, as_attachment=True)



@fillingForm.route('all_company/')
@login_required
def all_company():
    companies = Company.query.filter_by(owner_id=current_user.id)
    return render_template('showAllCreatedCompany.html', companies=companies, username=current_user.username)


@fillingForm.route('add_new_company/', methods=['GET', "POST"])
@login_required
def add_new_company():
    form = AddCompany()

    if form.validate_on_submit():
        newCompany = Company(owner_id=current_user.id, companyName=form.companyName.data)
        db.session.add(newCompany)

        # add one more company to the user ownCopmany data
        current_user_id = current_user.id
        user = User.query.filter_by(id=current_user_id).first()
        user.ownedCompany += 1
        db.session.commit()

        return redirect(url_for('fillingForm.home'))

    return render_template('addCompanyName.html', form=form)


@fillingForm.route('edit_form/<nar1_number>', methods=['GET', "POST"])
@login_required
def edit_form(nar1_number):
    selectedForm = Nar1data.query.filter_by(id=nar1_number).first()
    formOwner = Company.query.filter_by(id=selectedForm.company_id).first()

    if current_user.id != formOwner.owner_id:
        abort(403)
    else:
        form = Nar1Form(obj=selectedForm)

        if form.validate_on_submit():

            return redirect(url_for('fillingForm.home'))

        return render_template('nar1formTest.html', form=form)


# @fillingForm.route("funding_account/<>", methods=['GET', "POST"])
# @login_required
# def funding_account():
#     pass


# @fillingForm.route('upload_form/nar1/<company_id>', methods=['POST'])
# @login_required
# def uploadNar1(company_id):
#     file = request.files['inputFile']
#
#     newForm = Nar1pdf(name=file.filename, data=file.read(), company_id=company_id)
#     db.session.add(newForm)
#     db.session.commit()
#
#     return 'Saved already'


@fillingForm.route("edit_company_info/<company_id>", methods=['GET', "POST"])
@login_required
def edit_company_info(company_id):
    form = CompanyInfo()
    return render_template("edit_company_info.html", form=form, company_id=company_id)

companyFilling/templates/addCompanyName.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<form class="user" method="POST">

{{ form.hidden_tag() }}
{{ wtf.form_field(form.companyName) }}
{{ wtf.form_field(form.submit) }}

</form>

{% endblock %}

companyFilling/templates/addForm.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}



<div class="card shadow mb-4">

    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Nar1 form</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>Edit form</th>
                    <th>Nar1 Company name</th>
                    <th>Nar1 Business name</th>
                    <th>Download pdf</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th>Edit form</th>
                    <th>Nar1 Company name </th>
                    <th>Nar1 Business name</th>
                    <th>Download pdf</th>
                </tr>
                </tfoot>
                <tbody>

                {% for form in companyForm %}
                <tr>
                    <td><a href="{{ url_for('fillingForm.edit_form', nar1_number=form.id) }}">Edit</a></td>
                    <td>{{form.companyName}}</td>
                    <td><a href="#">{{ form.businessName }}</a></td>
                    <td><a href="{{ url_for('fillingForm.nar1_pdf_download', form_number=form.id) }}">Download</a> </td>

                </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>

<form class="user" method="POST">
    <input type="submit" name="action" value="new_form"></p>
</form>

{% endblock %}

companyFilling/templates/edit_company_info.html
<!DOCTYPE html>
<html>

{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}


<!-- Heading -->
<div class="container-fluid">

<div class="sidebar-heading">
    Company change:
</div>

<ul class="sidebar-dark accordion no-arrow" id="abc">
    <li style="font-size:30px" class="nav-item">
        <a class="collapsed" href="#" data-toggle="collapse" data-target="#companyName"
           aria-expanded="true" aria-controls="companyName">
            <i class="fas fa-fw fa-cog"></i>
            <span style="color:gray">Company Name</span>
        </a>
        <div id="companyName" class="collapse" aria-labelledby="headingTwo" data-parent="#abc">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="a.html">Change company name</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - shares change Collapse Menu -->
    <li style="font-size:30px" class="nav-item">
        <a class="collapsed" href="#" data-toggle="collapse" data-target="#sharesChange"
           aria-expanded="true" aria-controls="sharesChange">
            <i class="fas fa-fw fa-wrench"></i>
            <span style="color:gray">Shares Change</span>
        </a>
        <div id="sharesChange" class="collapse" aria-labelledby="a"
             data-parent="#abc">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item d-flex" href="{{ url_for('fillingForm.home') }}">Issue new shares</a>
                <a class="collapse-item" href="utilities-border.html">Transfer shares</a>
            </div>
        </div>
    </li>
    
    <!-- Nav Item - shares change Collapse Menu -->
    <li style="font-size:30px" class="nav-item">
        <a class="collapsed" href="#" data-toggle="collapse" data-target="#directorChange"
            aria-expanded="true" aria-controls="directorChange">
            <i class="fas fa-fw fa-wrench"></i>
            <span style="color:gray">Director Change</span>
        </a>
        <div id="directorChange" class="collapse" aria-labelledby="a"
            data-parent="#abc">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item d-flex" href="{{ url_for('changeDirector.remove_director', company_id=company_id) }}">Remove Director</a>
                <a class="collapse-item" href="{{ url_for('changeDirector.add_director', company_id=company_id) }}">Add Director</a>
            </div>
        </div>
    </li>
</ul>

</div>


{% endblock %}

</html>

companyFilling/templates/multi_step_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

companyFilling/templates/nar1formTest.html
<!DOCTYPE html>

{% import "bootstrap/wtf.html" as wtf %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>jQuery Steps Form</title>
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/smartwizard@5/dist/css/smart_wizard_all.min.css" rel="stylesheet" type="text/css" />
        <!-- Custom fonts for this template-->

    <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}" rel="stylesheet">

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/smartwizard@5/dist/js/jquery.smartWizard.min.js" type="text/javascript"></script>

</head>
<script type="text/javascript">
$(document).ready(function() {

    $('#smartwizard').smartWizard();

});
</script>

<body>

<div id="smartwizard">

    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" href="#step-1">
              Basic Company Info
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#step-2">
            Company Secretary
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#step-3">
            Directors
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#step-4">
            Step 4
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#step-4">
            Step 4
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#step-4">
            Step 4
          </a>
        </li>
    </ul>

    <div class="tab-content">
        <form method="post">
        <div id="step-1" class="tab-pane" role="tabpanel" aria-labelledby="step-1" >

                {{ form.hidden_tag() }}
                {{ wtf.form_field(form.companyName) }}
                {{ wtf.form_field(form.businessName) }}
                {{ wtf.form_field(form.companyType) }}
                {{ wtf.form_field(form.date1) }}
                {{ wtf.form_field(form.financialStatementStartDate) }}
                {{ wtf.form_field(form.financialStatementEndDate) }}
                {{ wtf.form_field(form.registeredOfficeAddress) }}
                {{ wtf.form_field(form.emailAddress) }}
                {{ wtf.form_field(form.submit) }}

        </div>
        <div id="step-2" class="tab-pane" role="tabpanel" aria-labelledby="step-2">
            {{ wtf.form_field(form.f50) }}
            {{ wtf.form_field(form.f51) }}
            {{ wtf.form_field(form.f52) }}
            {{ wtf.form_field(form.f53) }}
            {{ wtf.form_field(form.f61) }}
            Company Secretary
        </div>
        <div id="step-3" class="tab-pane" role="tabpanel" aria-labelledby="step-3">
            Directors
        </div>
        <div id="step-4" class="tab-pane" role="tabpanel" aria-labelledby="step-4">
            Step 4 Content
        </div>
            </form>
    </div>
</div>



</body>

</html>

companyFilling/templates/removeDirector.html
{% extends 'base.html' %}

{% block content %}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">All Directos</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Director Chinese Name</th>
                        <th>Director English Name</th>
                        <th>Remove Director</th>
                    </tr>
                </thead>

                <tfoot>
                    <tr>
                        <th>Director Chinese Name </th>
                        <th>Director English Name</th>
                        <th>Remove Director</th>
                    </tr>
                </tfoot>

                <tbody>

                {% for director in directors %}
                <tr>
                    <td>{{ director.directorNameInChinese }}</td>
                    <td>{{ director.directorNameInEnglish }}</td>
                    <td><a href="{{ url_for('changeDirector.remove', director_id=director.id) }}">Remove</a></td>

                </tr>


                {% endfor %}


                </tbody>
            </table>
        </div>
    </div>
</div>






{% endblock %}

companyFilling/templates/sample_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

companyFilling/templates/userPage.html
{% extends 'base.html' %}


{% block navBarItem %}

<li class="nav-item">
                <a class="nav-link" href="{{ url_for('fillingForm.home') }}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Fill new form</span></a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{{ url_for('fillingForm.add_new_company') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Add a new company</span></a>
</li>

{% endblock %}


{% block content %}

<h1>Hello {{ name }}</h1>

{% endblock %}