companyFilling/allDocument/forms.py
from wtforms import StringField, SelectField, TextAreaField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms import validators
from wtforms.validators import InputRequired, Length
from flask_wtf import FlaskForm


class SubmitButton(FlaskForm):
    submit = SubmitField("Submit Signature")

companyFilling/allDocument/routes.py
from flask import render_template, url_for, flash, redirect, send_file, Blueprint, abort, request
from flask_login import login_user, current_user, logout_user, login_required
from companyFilling.model import DirectorResignation, Company, Director, TestDB, DirectorChangeResolution
from companyFilling import db
from companyFilling.changeDirector.forms import DirectorInfo, Test
import os
import uuid
from datetime import date
from .forms import SubmitButton

allDocuments = Blueprint('allDocuments', __name__)


@allDocuments.route("DirectorChangeBoardResolution/<company_id>")
@login_required
def show_all(company_id):
    return render_template('allDocuments/show_all.html', company_id=company_id)


@allDocuments.route("all/DirectorChangeBoardResolution/<company_id>")
@login_required
def show_director_change_board_res(company_id):
    directors = DirectorChangeResolution.query.filter_by(company_id=company_id).all()
    return render_template("allDocuments/DirectorChangeBoardRes/show_all_res.html", directors=directors)


@allDocuments.route("Board_resolution/director_change/<uuid>")
def director_change_board_resolution(uuid):
    boardRes = DirectorChangeResolution.query.filter_by(uuid=uuid).first()
    directors = Director.query.filter_by(company_id=boardRes.company_id, capacity="Director", active="active").all()
    return render_template("allDocuments/DirectorChangeBoardRes/changeDirectorRes.html", info=boardRes, directors=directors,
                           uuid=uuid, one=1)


@allDocuments.route("send_to_directors/<company_id><uuid>")
@login_required
def send_to_directors(company_id, uuid):
    directors = Director.query.filter_by(company_id=company_id).all()
    allEmail = [i.directorEmail for i in directors]

    message = f"""Please head over to http://127.0.0.1:5000/documents/Board_resolution/director_change/{uuid} to
             sign the board resolution"""


@allDocuments.route('Board_resolution/director_change_pdf/<uuid>',  methods=['GET'])
@login_required
def view_board_resolution(uuid):
    import pdfkit
    from flask import make_response

    boardRes = DirectorChangeResolution.query.filter_by(uuid=uuid).first()
    directors = Director.query.filter_by(company_id=boardRes.company_id, capacity="Director", active="active").all()

    #path_wkhtmltopdf = "D:\website_research\wkhtmltopdf\\bin\wkhtmltopdf.exe"
    localpath_wkhtmltopdf = f"companyFilling\static\wkhtmltopdf.exe"

    config = pdfkit.configuration(wkhtmltopdf=localpath_wkhtmltopdf)
    options = {
        "disable-local-file-access": "",
        "enable-local-file-access": None
    }

    html = render_template('allDocuments/DirectorChangeBoardRes/changeDirectorRes.html', info=boardRes, directors=directors,
                           uuid=uuid)
    pdf = pdfkit.from_string(html, False, configuration=config, options=options)
    response = make_response(pdf)

    response.headers["Content-Type"] = "application/pdf"
    response.headers["Content-Disposition"] = "inline; filename=output.pdf"
    return response


@allDocuments.route('board_resolution/director_signature/<uuid><director_id>', methods=['POST', 'GET'])
def sign_board_resolution(uuid, director_id):
    form = SubmitButton()
    director = Director.query.filter_by(id=director_id).first()

    if form.validate_on_submit():
        data_uri = request.form.get('hidden')[22:]
        print(data_uri)

        # data_uri = request.get_json().get('dataUrl')
        # data_uri = data_uri[22:]
        filename = uuid + str(director_id)

        import base64
        with open(f"companyFilling/static/img/directorSignature/{filename}.png", 'wb') as f:
            f.write(base64.b64decode(data_uri))

        return redirect(url_for('fillingForm.all_company'))

    return render_template('allDocuments/DirectorChangeBoardRes/sign.html', director=director, form=form)


@allDocuments.route('director_resignation/<company_id>')
@login_required
def list_all_director_resignation(company_id):
    company = Company.query.filter_by(id=company_id).first()
    if company.owner_id != current_user.id:
        abort(403)
    directors = DirectorResignation.query.filter_by(company_id=company_id).all()

    return render_template('allDocuments/directorResign/show_all_res.html', directors=directors)


@allDocuments.route("director_resignation/letter/<uuid>")
def resignation_letter(uuid):
    director = DirectorResignation.query.filter_by(uuid=uuid).first()
    company = Company.query.filter_by(id=director.company_id).first()

    return render_template("allDocuments/directorResign/Directors_Resignation_Letter.html", director=director, company=company)

companyFilling/shareHolder/routes.py
from flask import render_template, url_for, flash, redirect, send_file, Blueprint, abort, request
from flask_login import login_user, current_user, logout_user, login_required
from companyFilling.model import Company, User, Nar1data, ShareHolderStake
from companyFilling import db
from companyFilling.fillingForm.forms import Nar1Form, AddCompany, aButton, CompanyInfo
from companyFilling.shareHolder.forms import ShareInfo, ShareCapitalForm


shareHolder = Blueprint('shareHolder', __name__)


@shareHolder.route("add_existing_shareholder/<hash><company_id>", methods=["POST", "GET"])
@login_required
def add_existing_shareholder(hash, company_id):
    form = ShareInfo()
    try:
        share_clas = ShareHolderStake.query.filter_by(company_id=company_id).all()
        share_classes = []
        for i in share_clas:
            if i.shareClass not in share_classes:
                share_classes.append(i.shareClass)
    except:
        share_classes = []

    if form.validate_on_submit():
        if request.form.get("shareOfClass") == "":
            shareClass = str(request.form.get('other_class'))
        else:
            shareClass = str(request.form.get("shareOfClass"))

        existingShareHolder = ShareHolderStake(name=form.name.data, shareClass=' '.join(shareClass.split()),
                                               totalShares=form.totalShares.data, address=form.address.data,
                                               company_id=company_id)
        db.session.add(existingShareHolder)
        db.session.commit()
        return redirect(url_for("fillingForm.edit_company_info", company_id=company_id))

    return render_template('shareHolder/addExistingShareHolder.html', company_id=company_id, form=form, share_classes=share_classes)


@shareHolder.route("all_share_holder/<company_id>")
@login_required
def show_shareholder(company_id):
    shareHolders = ShareHolderStake.query.filter_by(company_id=company_id).all()
    return render_template("shareHolder/showAllShareholder.html", shareHolders=shareHolders, company_id=company_id)


@shareHolder.route("edit/<shareHolder_id>/<company_id>", methods=["POST", "GET"])
@login_required
def edit_shareholder(shareHolder_id, company_id):
    try:
        share_clas = ShareHolderStake.query.filter_by(company_id=company_id).all()
        share_classes = []
        for i in share_clas:
            if i.shareClass not in share_classes:
                share_classes.append(i.shareClass)
    except:
        share_classes = []
    shareHolderInfo = ShareHolderStake.query.filter_by(id=shareHolder_id).first()

    form = ShareInfo(obj=shareHolderInfo)

    if form.validate_on_submit():
        obj = ShareHolderStake.query.filter_by(id=shareHolder_id).first()
        obj.name = form.name.data
        obj.address = form.address.data
        obj.shareClass = form.shareClass.data
        obj.totalShares = form.totalShares.data
        db.session.commit()
        return redirect(url_for("fillingForm.edit_company_info", company_id=company_id))

    return render_template("shareHolder/editShareHolder.html", id=shareHolder_id, form=form, share_classes=share_classes)


@shareHolder.route("transfer/<shareHolder_id>", methods=["POST", "GET"])
@login_required
def transfer_share(shareHolder_id):
    return render_template("shareHolder/transferShare")


@shareHolder.route("share_capital/<company_id>", methods=["POST", "GET"])
@login_required
def share_capital(company_id):
    try:
        share_clas = ShareHolderStake.query.filter_by(company_id=company_id).all()
        share_classes = []
        for i in share_clas:
            if i.shareClass not in share_classes:
                share_classes.append(i.shareClass)
    except:
        share_classes = []
    share_classes1 = [i.replace(" ", "_") for i in share_classes]

    return render_template('shareHolder/shareCapital.html', share_classes=share_classes1, company_id=company_id)


@shareHolder.route("edit_share_capital/addInfo/<company_id>/<share_class>", methods=["POST", "GET"])
@login_required
def edit_share_capital(company_id, share_class):
    shareClass = share_class.replace("_"," ")

    shareClassRow = ShareHolderStake.query.filter_by(company_id=company_id, shareClass=shareClass).all()

    totalClassShare = 0
    for i in shareClassRow:
        totalClassShare += i.totalShares

    # try:
    #     share_clas = ShareHolderStake.query.filter_by(company_id=company_id).all()
    #     share_classes = []
    #     for i in share_clas:
    #         if i.shareClass not in share_classes:
    #             share_classes.append(i.shareClass)
    # except:
    #     share_classes = []

    return render_template('shareHolder/addShareCapital.html', share_classes=shareClass, company_id=company_id,
                                                               total_share=totalClassShare)

companyFilling/templates/allDocuments/email_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

companyFilling/templates/allDocuments/show_all.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<!-- Heading -->
<div class="container-fluid">


<ul class="sidebar-dark accordion no-arrow" id="abc">
    <li style="font-size:30px" class="nav-item">
        <a class="collapsed" href="#" data-toggle="collapse" data-target="#companyName"
           aria-expanded="true" aria-controls="companyName">
            <i class="fas fa-fw fa-cog"></i>
            <span style="color:gray">Company Name</span>
        </a>
        <div id="companyName" class="collapse" aria-labelledby="headingTwo" data-parent="#abc">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="a.html">Change company name</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - shares change Collapse Menu -->
    <li style="font-size:30px" class="nav-item">
        <a class="collapsed" href="#" data-toggle="collapse" data-target="#sharesChange"
           aria-expanded="true" aria-controls="sharesChange">
            <i class="fas fa-fw fa-wrench"></i>
            <span style="color:gray">Shares Change</span>
        </a>
        <div id="sharesChange" class="collapse" aria-labelledby="a"
             data-parent="#abc">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item d-flex" href="{{ url_for('shareHolder.add_existing_shareholder', company_id=company_id, hash=hash)}}">Add existing shareholder</a>
                <a class="collapse-item d-flex" href="{{ url_for('fillingForm.home') }}">Issue new shares</a>
                <a class="collapse-item d-flex" href="{{ url_for('shareHolder.show_shareholder', company_id=company_id) }}">Edit/View shareholder information</a>
                <a class="collapse-item d-flex" href="{{ url_for('shareHolder.transfer_share', company_id=company_id) }}">Transfer shares</a>
                <a class="collapse-item d-flex" href="{{ url_for('shareHolder.share_capital', company_id=company_id) }}">Add share capital Info</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - shares change Collapse Menu -->
    <li style="font-size:30px" class="nav-item">
        <a class="collapsed" href="#" data-toggle="collapse" data-target="#directorChange"
            aria-expanded="true" aria-controls="directorChange">
            <i class="fas fa-fw fa-wrench"></i>
            <span style="color:gray">Director</span>
        </a>
        <div id="directorChange" class="collapse" aria-labelledby="a"
            data-parent="#abc">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item d-flex" href="{{ url_for('allDocuments.show_director_change_board_res', company_id=company_id) }}">Replace/Remove Director Board Resolution</a>
                <a class="collapse-item d-flex" href="{{ url_for('allDocuments.list_all_director_resignation', company_id=company_id) }}">Director Resignation Letter</a>
                <a class="collapse-item d-flex" href="{{ url_for('changeDirector.add_director_corp', company_id=company_id) }}">Add Director (Body Corporate)</a>
                <a class="collapse-item d-flex" href="#">Edit Director Info</a>
            </div>
        </div>
    </li>

    <li style="font-size:30px" class="nav-item">
        <a class="collapsed" href="#" data-toggle="collapse" data-target="#companySecretary"
            aria-expanded="true" aria-controls="companySecretary">
            <i class="fas fa-fw fa-wrench"></i>
            <span style="color:gray">Company Secretary</span>
        </a>
        <div id="companySecretary" class="collapse" aria-labelledby="a"
            data-parent="#abc">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item d-flex" href="{{ url_for('companySecretary.new_secretary', company_id=company_id) }}">Change/Add Company Secretary</a>
                <a class="collapse-item d-flex" href="">Edit Secretary Info</a>
            </div>
        </div>
    </li>
</ul>

</div>

{% endblock %}