companyFilling/allDocument/forms.py
from wtforms import StringField, SelectField, TextAreaField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms import validators
from wtforms.validators import InputRequired, Length
from flask_wtf import FlaskForm


class SubmitButton(FlaskForm):
    submit = SubmitField("Submit Signature")

companyFilling/allDocument/routes.py
from flask import render_template, url_for, flash, redirect, send_file, Blueprint, abort, request
from flask_login import login_user, current_user, logout_user, login_required
from companyFilling.model import DirectorResignation, Company, Director, TestDB, DirectorChangeResolution
from companyFilling import db
from companyFilling.changeDirector.forms import DirectorInfo, Test
import os
import uuid
from datetime import date
from .forms import SubmitButton

allDocuments = Blueprint('allDocuments', __name__)


@allDocuments.route("DirectorChangeBoardResolution/<company_id>")
@login_required
def show_all(company_id):
    return render_template('allDocuments/show_all.html', company_id=company_id)


@allDocuments.route("all/DirectorChangeBoardResolution/<company_id>")
@login_required
def show_director_change_board_res(company_id):
    directors = DirectorChangeResolution.query.filter_by(company_id=company_id).all()
    return render_template("allDocuments/DirectorChangeBoardRes/show_all_res.html", directors=directors)


@allDocuments.route("Board_resolution/director_change/<uuid>")
def director_change_board_resolution(uuid):
    boardRes = DirectorChangeResolution.query.filter_by(uuid=uuid).first()
    directors = Director.query.filter_by(company_id=boardRes.company_id, capacity="Director", active="active").all()
    return render_template("allDocuments/DirectorChangeBoardRes/changeDirectorRes.html", info=boardRes, directors=directors,
                           uuid=uuid, one=1)


@allDocuments.route("send_to_directors/<company_id><uuid>")
@login_required
def send_to_directors(company_id, uuid):
    directors = Director.query.filter_by(company_id=company_id).all()
    allEmail = [i.directorEmail for i in directors]

    message = f"""Please head over to http://127.0.0.1:5000/documents/Board_resolution/director_change/{uuid} to
             sign the board resolution"""


@allDocuments.route('Board_resolution/director_change_pdf/<uuid>',  methods=['GET'])
@login_required
def view_board_resolution(uuid):
    import pdfkit
    from flask import make_response

    boardRes = DirectorChangeResolution.query.filter_by(uuid=uuid).first()
    directors = Director.query.filter_by(company_id=boardRes.company_id, capacity="Director", active="active").all()

    #path_wkhtmltopdf = "D:\website_research\wkhtmltopdf\\bin\wkhtmltopdf.exe"
    localpath_wkhtmltopdf = f"companyFilling\static\wkhtmltopdf.exe"

    config = pdfkit.configuration(wkhtmltopdf=localpath_wkhtmltopdf)
    options = {
        "disable-local-file-access": "",
        "enable-local-file-access": None
    }

    html = render_template('allDocuments/DirectorChangeBoardRes/changeDirectorRes.html', info=boardRes, directors=directors,
                           uuid=uuid)
    pdf = pdfkit.from_string(html, False, configuration=config, options=options)
    response = make_response(pdf)

    response.headers["Content-Type"] = "application/pdf"
    response.headers["Content-Disposition"] = "inline; filename=output.pdf"
    return response


@allDocuments.route('board_resolution/director_signature/<uuid><director_id>', methods=['POST', 'GET'])
def sign_board_resolution(uuid, director_id):
    form = SubmitButton()
    director = Director.query.filter_by(id=director_id).first()

    if form.validate_on_submit():
        data_uri = request.form.get('hidden')[22:]
        print(data_uri)

        # data_uri = request.get_json().get('dataUrl')
        # data_uri = data_uri[22:]
        filename = uuid + str(director_id)

        import base64
        with open(f"companyFilling/static/img/directorSignature/{filename}.png", 'wb') as f:
            f.write(base64.b64decode(data_uri))

        return redirect(url_for('fillingForm.all_company'))

    return render_template('allDocuments/DirectorChangeBoardRes/sign.html', director=director, form=form)


@allDocuments.route('director_resignation/<company_id>')
@login_required
def list_all_director_resignation(company_id):
    company = Company.query.filter_by(id=company_id).first()
    if company.owner_id != current_user.id:
        abort(403)
    directors = DirectorResignation.query.filter_by(company_id=company_id).all()

    return render_template('allDocuments/directorResign/show_all_res.html', directors=directors)


@allDocuments.route("director_resignation/letter/<uuid>")
def resignation_letter(uuid):
    director = DirectorResignation.query.filter_by(uuid=uuid).first()
    company = Company.query.filter_by(id=director.company_id).first()

    return render_template("allDocuments/directorResign/Directors_Resignation_Letter.html", director=director, company=company)

companyFilling/templates/allDocuments/DirectorChangeBoardRes/changeDirectorRes.html
<!DOCTYPE html>
<html lang="en">
<style>

a:link, a:visited {
    color: black;
}

.notbold{
    font-weight:normal
}​

</style>

	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!--bootstrap 5-->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
		<!--This is the board resolution for the scnario where there is change of direcotrs / company secretary-->
		<title>Board Resolution</title>
	</head>
	<body>
		<div class="container text-center">
			<br>
			<!--Please use the company name, place holder here for this h2 tag-->
			<h1>{{ info.companyName}}</h1>
			<p><i>(Incorporated in Hong Kong with limited liability)</i>
				<br>
				<i>(the "<b>Company</b>")</i>
			</p>
		</div>

		<div class="container text-center">
			<p>RESOLUTIONS IN WRITING OF THE DIRECTOR(S) PASSED PURUSANT TO THE ARTICLES OF ASSOCIATION OF THE COMPANY
			</p>
			<!--Please note {{date_passed_resolution}} needs to be a date when this resolution is passed-->
			<p>DATED {{ info.date_passed_resolution }}</p>
			<hr>
		</div>

		<div class="container">
			<p>
				The undersigned, being the director(s) of the Company (the "<b>Director(s)</b>", and each individually a "<b>Director</b>") hereby take the following actions and consent to the passing of the following resolutions:
			</p>
		</div>
		<!--Here begins the resolutions-->
		<div class="container">
			<ol>
				<li><b>DIRECTORS' INTEREST</b></li>
				<p>IT IS NOTED THAT the Director(s) by their signatures below confirm that they haave declared their interest (if any) in relation to the matters as described below in the manner required by the articles of association of the Company and the Companies Ordinance (Cap. 622)</p>
				<!--This is for the resignation of directors/ Company Secretary, please input the name-->
				<li><b>RESIGNATION OF DIRECTOR(s)</b></li>
				<p>IT IS NOTED THAT {{ info.resignDirector }} (the "<b>Resigning Director(s)</b>") has tendered his resignation as Director of the Company with effect from {{date_passed_resolution}} (the "<b>Effective Date</b>")</p>
				<p>IT IS RESOLVED THAT:
					<ol type="a">
						<li>the resignation of Resigning Director(s) as Director of the Company with effect from the Effective Date be accepted; and</li>
						<li>the Resigning Director be removed as an authorised signatory (if applicable) of all banks accounts of the Company with effect from the Effective Date.</li>
					</ol>
				</p>
				<li><b>APPOINTMENT OF DIRECTOR(s)</b></li>
				<!--New Directors are contained here in the {{New_Directors}}-->
				<p>IT IS NOTED THAT it is proposed that the Company appoints the following persons:{{info.newDirector}} (each a "<b>New Director</b>"), as new director(s) of the Company with effect from the Effective Date.</p>
				<p>IT IS RESOLVED THAT:
					<ol type="a">
						<li>with effect from the Effective Date, each New Director, having consented so to act, be appointed as a director of the Company.</li>
					</ol>
				</p>

				<li><b>GENERAL AUTHORISATION</b></li>
				<p>IT IS RESOLVED THAT:
					<ol type="a">
						<li>all the relevant registers, including but not limited to register of directors and register of company secretary, shall be updated accordingly.</li>
						<li>in connection with foregoing resolutions, each Director be, and such other persons as authorized by any Director be,  authorized in the name and on behalf of the Company, to do such further things as such Director deems necessary or appropriate, including but not limited to do and perform (or caused to be done and performed), in the name and on behalf of the Company, all such acts and to sign, make, execute, deliver issue or file (or cause to be signed, made, executed, delivered, issued or filed) with any person including any governmental authority or agency, all such agreements, documents, instruments, certificates, consents or waivers and to pay, or cause to be paid, all such payments, as any of them may deem necessary or advisable in order to carry out the intent of the above resolutions, the authority for the doing of any such things and the signing, making, execution, delivery, issue and filing of such of the foregoing to be conclusively evidenced hereby; and</li>
						<li>any and all actions of the Company, or of any Director, taken in connection with the actions contemplated by the foregoing resolutions prior to the execution hereof be and are hereby ratified, confirmed, approved and adopted in all respects as are fully as if such action(s) had been presented to for approval and approved by, the board of directors of the Company prior to such action being taken.</li>
					</ol>
				</ol>
				<p class="text-center"><i>(To be followed by signatures of all Director(s))</i></p>
				<!--Here, we make signatures block for each director. Consider we may replace it with e-signature. Note that the number of signatures block depend on the number of directors-->
				{% for director in directors %}
				<div class="container">
					<br><br>
					{% set imageLink = 'img/directorSignature/' + uuid + director.id|string + '.png' %}
					<img src="{{url_for('static', filename=imageLink, _external=True) }}" width="580" height="130">
					<p>_________________________________________________</p>
					<!--Note: Existing Directors-->
					<p><b>{% if director.companyOrPerson == "Corporate" %}
								<a href="{{ url_for('allDocuments.sign_board_resolution', uuid=uuid, director_id=director.id)}}" style="text-decoration:none"><span class="notbold">{{ director.directorOtherName }}</span></a>
							{% else %}
								<a href="{{ url_for('allDocuments.sign_board_resolution', uuid=uuid, director_id=director.id)}}" style="text-decoration:none"><span class="notbold">{{ director.directorOtherName }} {{ director.directorSurname }}</span></a>
							{% endif %}
					</b>
						<br>
						{% if director.capacity == "AlternateDirector" %}
							Alternate Director
						{% else %}
							Director
						{% endif %}
						{{director.id}}
					</p>
				</div>
				{% endfor %}
			</div>
		<ul></ul>
	</body>
</html>

companyFilling/templates/allDocuments/DirectorChangeBoardRes/show_all_res.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">All Directos</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Date Created</th>
                        <th>View signature</th>
                        <th>View Pdf</th>
                        <th>Send email</th>
                    </tr>
                </thead>

                <tfoot>
                    <tr>
                        <th>Date Created</th>
                        <th>View signature</th>
                        <th>View Pdf</th>
                        <th>Send email</th>
                    </tr>
                </tfoot>

                <tbody>

                {% for director in directors %}
                <tr>
                    <td>{{ director.date_passed_resolution }}</td>
                    <td><a href="{{ url_for('allDocuments.director_change_board_resolution', uuid=director.uuid) }}">View Signature</a></td>
                    <td><a href="{{ url_for('allDocuments.view_board_resolution', uuid=director.uuid)}}">View PDF</a></td>
                    <td><a href="">Send</a></td>
                </tr>


                {% endfor %}


                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

companyFilling/templates/allDocuments/DirectorChangeBoardRes/sign.html
<!DOCTYPE html>
<html lang="en">

{% import "bootstrap/wtf.html" as wtf %}

<style>
#sig-canvas {
  border: 2px dotted #CCCCCC;
  border-radius: 15px;
  cursor: crosshair;
}
</style>

<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    {% if director.directorSurname is none %}
        <h2>Director: {{director.directorOtherName}}</h2>
    {% else %}
        <h2>Director: {{director.directorOtherName}} {{director.directorSurname}}</h2>
    {% endif %}


  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>E-Signature</h1>
        <p>Sign in the canvas below and save your signature as an image!</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <canvas id="sig-canvas" width="620" height="160">
          Get a better browser, bro.
        </canvas>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <button class="btn btn-primary" id="sig-submitBtn">Review Signature</button>
        <button class="btn btn-default" id="sig-clearBtn">Clear Signature</button>
      </div>
    </div>
    <br/>

    <form method="POST">
      {{ form.hidden_tag() }}
      {{ wtf.form_field(form.submit) }}

      <input type="hidden" name="hidden" id="Result">

      <div class="row">
        <div class="col-md-12">
          <textarea id="sig-dataUrl" class="form-control" rows="5">Data URL for your signature will go here</textarea>
        </div>
      </div>
    </form>

    <br/>
    <div class="row">
      <div class="col-md-12">
        <img id="sig-image" src="" alt="Your signature will go here!"/>
      </div>
    </div>
  </div>


</body>

<script language="JavaScript">
    (function() {
  window.requestAnimFrame = (function(callback) {
    return window.requestAnimationFrame ||
      window.webkitRequestAnimationFrame ||
      window.mozRequestAnimationFrame ||
      window.oRequestAnimationFrame ||
      window.msRequestAnimaitonFrame ||
      function(callback) {
        window.setTimeout(callback, 1000 / 60);
      };
  })();

  var canvas = document.getElementById("sig-canvas");
  var ctx = canvas.getContext("2d");
  ctx.strokeStyle = "#222222";
  ctx.lineWidth = 4;

  var drawing = false;
  var mousePos = {
    x: 0,
    y: 0
  };
  var lastPos = mousePos;

  canvas.addEventListener("mousedown", function(e) {
    drawing = true;
    lastPos = getMousePos(canvas, e);
  }, false);

  canvas.addEventListener("mouseup", function(e) {
    drawing = false;
  }, false);

  canvas.addEventListener("mousemove", function(e) {
    mousePos = getMousePos(canvas, e);
  }, false);

  // Add touch event support for mobile
  canvas.addEventListener("touchstart", function(e) {

  }, false);

  canvas.addEventListener("touchmove", function(e) {
    var touch = e.touches[0];
    var me = new MouseEvent("mousemove", {
      clientX: touch.clientX,
      clientY: touch.clientY
    });
    canvas.dispatchEvent(me);
  }, false);

  canvas.addEventListener("touchstart", function(e) {
    mousePos = getTouchPos(canvas, e);
    var touch = e.touches[0];
    var me = new MouseEvent("mousedown", {
      clientX: touch.clientX,
      clientY: touch.clientY
    });
    canvas.dispatchEvent(me);
  }, false);

  canvas.addEventListener("touchend", function(e) {
    var me = new MouseEvent("mouseup", {});
    canvas.dispatchEvent(me);
  }, false);

  function getMousePos(canvasDom, mouseEvent) {
    var rect = canvasDom.getBoundingClientRect();
    return {
      x: mouseEvent.clientX - rect.left,
      y: mouseEvent.clientY - rect.top
    }
  }

  function getTouchPos(canvasDom, touchEvent) {
    var rect = canvasDom.getBoundingClientRect();
    return {
      x: touchEvent.touches[0].clientX - rect.left,
      y: touchEvent.touches[0].clientY - rect.top
    }
  }

  function renderCanvas() {
    if (drawing) {
      ctx.moveTo(lastPos.x, lastPos.y);
      ctx.lineTo(mousePos.x, mousePos.y);
      ctx.stroke();
      lastPos = mousePos;
    }
  }

  // Prevent scrolling when touching the canvas
  document.body.addEventListener("touchstart", function(e) {
    if (e.target == canvas) {
      e.preventDefault();
    }
  }, false);
  document.body.addEventListener("touchend", function(e) {
    if (e.target == canvas) {
      e.preventDefault();
    }
  }, false);
  document.body.addEventListener("touchmove", function(e) {
    if (e.target == canvas) {
      e.preventDefault();
    }
  }, false);

  (function drawLoop() {
    requestAnimFrame(drawLoop);
    renderCanvas();
  })();

  function clearCanvas() {
    canvas.width = canvas.width;
  }

  // Set up the UI
  var sigText = document.getElementById("sig-dataUrl");
  var sigImage = document.getElementById("sig-image");
  var clearBtn = document.getElementById("sig-clearBtn");
  var submitBtn = document.getElementById("sig-submitBtn");
  clearBtn.addEventListener("click", function(e) {
    clearCanvas();
    sigText.innerHTML = "Data URL for your signature will go here!";
    sigImage.setAttribute("src", "");
  }, false);
  submitBtn.addEventListener("click", function(e) {
    var dataUrl = canvas.toDataURL();

    document.getElementById("Result").value = dataUrl;

    sigText.innerHTML = dataUrl;
    sigImage.setAttribute("src", dataUrl);
  }, false);

})();
</script>

</html>